# Generated by Django 5.2.17 on 2026-09-19 18:12

import InvenTree.fields
import InvenTree.validators
import django.core.validators
import django.db.models.deletion
import djmoney.models.validators
import mptt.fields
import part.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0154_remove_part_notes'),
        ('stock', '0128_remove_stockitem_notes'),
        ('users', '0017_apitoken_hmac_digest_apitoken_issued_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='partcategory',
            options={'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='partcategoryparametertemplate',
            options={'verbose_name': 'Product Category Parameter Template'},
        ),
        migrations.AlterModelOptions(
            name='partinternalpricebreak',
            options={'verbose_name': 'Product Internal Price Break'},
        ),
        migrations.AlterModelOptions(
            name='partsellpricebreak',
            options={'verbose_name': 'Product Sale Price Break'},
        ),
        migrations.AlterModelOptions(
            name='parttesttemplate',
            options={'verbose_name': 'Product Test Template'},
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='allow_variants',
            field=models.BooleanField(default=False, help_text='Stock items for variant products can be used for this BOM item', verbose_name='Allow Variants'),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='inherited',
            field=models.BooleanField(default=False, help_text='This BOM item is inherited by BOMs for variant products', verbose_name='Gets inherited'),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='part',
            field=models.ForeignKey(help_text='Select parent product', limit_choices_to={'assembly': True}, on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='part.part', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='raw_amount',
            field=models.CharField(help_text='Amount of sub-product consumed to produce one product', max_length=25, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='sub_part',
            field=models.ForeignKey(help_text='Select product to be used in BOM', limit_choices_to={'component': True}, on_delete=django.db.models.deletion.CASCADE, related_name='used_in', to='part.part', verbose_name='Sub product'),
        ),
        migrations.AlterField(
            model_name='bomitemsubstitute',
            name='part',
            field=models.ForeignKey(help_text='Substitute product', limit_choices_to={'component': True}, on_delete=django.db.models.deletion.CASCADE, related_name='substitute_items', to='part.part', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='part',
            name='IPN',
            field=models.CharField(blank=True, help_text='Internal Product Number', max_length=100, null=True, verbose_name='IPN'),
        ),
        migrations.AlterField(
            model_name='part',
            name='active',
            field=models.BooleanField(default=True, help_text='Is this product active?', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='part',
            name='assembly',
            field=models.BooleanField(default=part.settings.part_assembly_default, help_text='Can this product be built from other products?', verbose_name='Assembly'),
        ),
        migrations.AlterField(
            model_name='part',
            name='bom_validated',
            field=models.BooleanField(default=False, help_text='Is the BOM for this product valid?', verbose_name='BOM Validated'),
        ),
        migrations.AlterField(
            model_name='part',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Product category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parts', to='part.partcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='part',
            name='component',
            field=models.BooleanField(default=part.settings.part_component_default, help_text='Can this product be used to build other products?', verbose_name='Component'),
        ),
        migrations.AlterField(
            model_name='part',
            name='consumable',
            field=models.BooleanField(default=False, help_text='Is this product consumable, such as glue or a fastener?', verbose_name='Consumable'),
        ),
        migrations.AlterField(
            model_name='part',
            name='default_expiry',
            field=models.PositiveIntegerField(default=0, help_text='Expiry time (in days) for stock items of this product', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Default Expiry'),
        ),
        migrations.AlterField(
            model_name='part',
            name='description',
            field=models.CharField(blank=True, help_text='Product description (optional)', max_length=250, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='part',
            name='is_template',
            field=models.BooleanField(default=part.settings.part_template_default, help_text='Is this product a template product?', verbose_name='Is Template'),
        ),
        migrations.AlterField(
            model_name='part',
            name='keywords',
            field=models.CharField(blank=True, help_text='Product keywords to improve visibility in search results', max_length=250, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='part',
            name='locked',
            field=models.BooleanField(default=False, help_text='Locked products cannot be edited', verbose_name='Locked'),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(help_text='Product name', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='part',
            name='purchaseable',
            field=models.BooleanField(default=part.settings.part_purchaseable_default, help_text='Can this product be purchased from external suppliers?', verbose_name='Purchaseable'),
        ),
        migrations.AlterField(
            model_name='part',
            name='responsible_owner',
            field=models.ForeignKey(blank=True, help_text='Owner responsible for this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts_responsible', to='users.owner', verbose_name='Responsible'),
        ),
        migrations.AlterField(
            model_name='part',
            name='revision',
            field=models.CharField(blank=True, help_text='Product revision or version number', max_length=100, null=True, verbose_name='Revision'),
        ),
        migrations.AlterField(
            model_name='part',
            name='revision_of',
            field=models.ForeignKey(blank=True, help_text='Is this product a revision of another product?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='part.part', verbose_name='Revision Of'),
        ),
        migrations.AlterField(
            model_name='part',
            name='salable',
            field=models.BooleanField(default=part.settings.part_salable_default, help_text='Can this product be sold to customers?', verbose_name='Salable'),
        ),
        migrations.AlterField(
            model_name='part',
            name='testable',
            field=models.BooleanField(default=False, help_text='Can this product have test results recorded against it?', verbose_name='Testable'),
        ),
        migrations.AlterField(
            model_name='part',
            name='trackable',
            field=models.BooleanField(default=part.settings.part_trackable_default, help_text='Does this product have tracking for unique items?', verbose_name='Trackable'),
        ),
        migrations.AlterField(
            model_name='part',
            name='units',
            field=models.CharField(blank=True, default='', help_text='Units of measure for this product', max_length=20, null=True, validators=[InvenTree.validators.validate_physical_units], verbose_name='Units'),
        ),
        migrations.AlterField(
            model_name='part',
            name='variant_of',
            field=models.ForeignKey(blank=True, help_text='Is this product a variant of another product?', limit_choices_to={'is_template': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='part.part', verbose_name='Variant Of'),
        ),
        migrations.AlterField(
            model_name='part',
            name='virtual',
            field=models.BooleanField(default=part.settings.part_virtual_default, help_text='Is this a virtual product, such as a software product or license?', verbose_name='Virtual'),
        ),
        migrations.AlterField(
            model_name='partcategory',
            name='default_keywords',
            field=models.CharField(blank=True, help_text='Default keywords for products in this category', max_length=250, null=True, verbose_name='Default keywords'),
        ),
        migrations.AlterField(
            model_name='partcategory',
            name='default_location',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Default location for products in this category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_categories', to='stock.stocklocation', verbose_name='Default Location'),
        ),
        migrations.AlterField(
            model_name='partcategoryparametertemplate',
            name='category',
            field=models.ForeignKey(help_text='Product Category', on_delete=django.db.models.deletion.CASCADE, related_name='parameter_templates', to='part.partcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='partinternalpricebreak',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internalpricebreaks', to='part.part', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='partpricing',
            name='bom_cost_max',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=6, default_currency='', help_text='Maximum cost of component products', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Maximum BOM Cost'),
        ),
        migrations.AlterField(
            model_name='partpricing',
            name='bom_cost_min',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=6, default_currency='', help_text='Minimum cost of component products', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Minimum BOM Cost'),
        ),
        migrations.AlterField(
            model_name='partpricing',
            name='part',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_data', to='part.part', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='partpricing',
            name='supplier_price_max',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=6, default_currency='', help_text='Maximum price of product from external suppliers', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Maximum Supplier Price'),
        ),
        migrations.AlterField(
            model_name='partpricing',
            name='supplier_price_min',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=6, default_currency='', help_text='Minimum price of product from external suppliers', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Minimum Supplier Price'),
        ),
        migrations.AlterField(
            model_name='partpricing',
            name='variant_cost_max',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=6, default_currency='', help_text='Calculated maximum cost of variant products', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Maximum Variant Cost'),
        ),
        migrations.AlterField(
            model_name='partpricing',
            name='variant_cost_min',
            field=InvenTree.fields.InvenTreeModelMoneyField(blank=True, currency_choices=[], decimal_places=6, default_currency='', help_text='Calculated minimum cost of variant products', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Minimum Variant Cost'),
        ),
        migrations.AlterField(
            model_name='partrelated',
            name='part_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_parts_1', to='part.part', verbose_name='Product 1'),
        ),
        migrations.AlterField(
            model_name='partrelated',
            name='part_2',
            field=models.ForeignKey(help_text='Select Related Product', on_delete=django.db.models.deletion.CASCADE, related_name='related_parts_2', to='part.part', verbose_name='Product 2'),
        ),
        migrations.AlterField(
            model_name='partsellpricebreak',
            name='part',
            field=models.ForeignKey(limit_choices_to={'salable': True}, on_delete=django.db.models.deletion.CASCADE, related_name='salepricebreaks', to='part.part', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='partstar',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starred_users', to='part.part', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='partstocktake',
            name='part',
            field=models.ForeignKey(help_text='Product for stocktake', on_delete=django.db.models.deletion.CASCADE, related_name='stocktakes', to='part.part', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='parttesttemplate',
            name='part',
            field=models.ForeignKey(limit_choices_to={'testable': True}, on_delete=django.db.models.deletion.CASCADE, related_name='test_templates', to='part.part', verbose_name='Product'),
        ),
    ]
