# Generated by Django 5.2.17 on 2026-09-19 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0081_remove_company_notes_remove_manufacturerpart_notes_and_more'),
        ('part', '0155_alter_part_options_alter_partcategory_options_and_more'),
        ('stock', '0128_remove_stockitem_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleTypeMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_type', models.CharField(choices=[('b2b_credit', 'B2B Credit'), ('b2c_cash', 'B2C Cash'), ('b2c_online', 'B2C Online'), ('gift', 'Gift'), ('restock', 'Restock'), ('correction', 'Correction')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=5, max_digits=15)),
                ('unit_value', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('total_value', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='company.company')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='part.part')),
                ('tracking_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale_type_movement', to='stock.stockitemtracking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
