# Generated by Django 5.2.17 on 2026-09-20 04:19

import django.db.models.deletion
import django.utils.timezone
import stationery_sales.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0081_remove_company_notes_remove_manufacturerpart_notes_and_more'),
        ('stationery_sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_int', models.BigIntegerField(default=0)),
                ('reference', models.CharField(default=stationery_sales.validators.generate_next_invoice_reference, max_length=64, unique=True, validators=[stationery_sales.validators.validate_invoice_reference])),
                ('invoice_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField()),
                ('total', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='unpaid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(limit_choices_to={'is_customer': True}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='company.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stationery_sales.invoice')),
                ('sale_type_movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_line', to='stationery_sales.saletypemovement')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=5, max_digits=15)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online'), ('cheque', 'Cheque')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='stationery_sales.invoice')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['payment_date', 'created_at'],
            },
        ),
    ]
